In [1]:
import pandas as pd

file = 'IRIS.csv'

df = pd.read_csv(file)

In [2]:
df.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
means_array = df.mean()
covariance_matrix = df.cov()

In [ ]:
# # prompt
# I want to use multivariate kde for synthetic data generation 

# with mean as each number of dataset and bandwidth as 1 and use the concept of covariance as needed

# give me descriptive code in python with nice modularity

# the data is collected from .csv file
# 0	5.1	3.5	1.4	0.2	Iris-setosa
# 1	4.9	3.0	1.4	0.2	Iris-setosa
# 2	4.7	3.2	1.3	0.2	Iris-setosa

# this is the dataset to consider for e.g.

In [4]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KernelDensity
from scipy.stats import multivariate_normal

# Load CSV data
def load_data(file_path):
    """
    Load the Iris dataset from a CSV file and preprocess the numeric values.
    
    Parameters:
        file_path (str): The path to the CSV file.
        
    Returns:
        data (pd.DataFrame): A dataframe containing the numeric data only.
    """
    data = pd.read_csv(file_path, header=None)
    numeric_data = data.iloc[:, :-1].values  # Exclude the index and the class label
    return numeric_data

# Fit KDE for data generation
def fit_kde(data, bandwidth=1.0):
    """
    Fit the Kernel Density Estimation (KDE) model with a Gaussian kernel.
    
    Parameters:
        data (np.array): The original dataset for KDE.
        bandwidth (float): The bandwidth parameter for KDE (default: 1.0).
        
    Returns:
        kde_model (KernelDensity): Fitted KDE model.
    """
    kde_model = KernelDensity(bandwidth=bandwidth, kernel='gaussian')
    kde_model.fit(data)
    return kde_model

# Generate synthetic data using KDE
def generate_synthetic_data(kde_model, n_samples):
    """
    Generate synthetic data using the fitted KDE model.
    
    Parameters:
        kde_model (KernelDensity): Fitted KDE model.
        n_samples (int): Number of synthetic samples to generate.
        
    Returns:
        synthetic_data (np.array): Generated synthetic dataset.
    """
    synthetic_data = kde_model.sample(n_samples)
    return synthetic_data

# Add covariance to adjust synthetic data (optional)
def adjust_with_covariance(original_data, synthetic_data):
    """
    Adjust the generated synthetic data using the covariance matrix of the original data.
    
    Parameters:
        original_data (np.array): The original dataset for reference.
        synthetic_data (np.array): The synthetic dataset generated from KDE.
        
    Returns:
        adjusted_synthetic_data (np.array): Adjusted synthetic data based on covariance.
    """
    cov_matrix = np.cov(original_data.T)
    mean_vector = np.mean(original_data, axis=0)
    
    adjusted_synthetic_data = []
    for sample in synthetic_data:
        adjusted_sample = multivariate_normal(mean=mean_vector, cov=cov_matrix).rvs()
        adjusted_synthetic_data.append(adjusted_sample)
    
    return np.array(adjusted_synthetic_data)

# # Function to save synthetic data to a new CSV file
def save_synthetic_data(original_df, synthetic_data, output_file):
    """Saves synthetic data to a new CSV file."""
    synthetic_df = pd.DataFrame(np.round(synthetic_data, 2), columns=['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth'])
#     synthetic_df['Species'] = np.random.choice(original_df['Species'], size=len(synthetic_df))  # Randomly assign species
#     synthetic_df.index.name = 'Index'  # Add index as in the original data
    synthetic_df['Species'] = "Iris-virginica"
    synthetic_df.to_csv(output_file, index=False)
    print(f"Synthetic data saved to {output_file}")
    
# Main function to combine all steps
def main(file_path, output_file, n_samples=500, bandwidth=1.0):
    """
    Main function to execute the data generation process.
    
    Parameters:
        file_path (str): Path to the CSV file containing the dataset.
        n_samples (int): Number of synthetic samples to generate (default: 100).
        bandwidth (float): Bandwidth for KDE (default: 1.0).
        
    Returns:
        final_synthetic_data (np.array): Final synthetic data after adjustments.
    """
    
    # Load and preprocess data
    df = load_data(file_path)
    
    # Fit KDE model
    kde_model = fit_kde(df, bandwidth=bandwidth)
    
    # Generate synthetic data
    synthetic_data = generate_synthetic_data(kde_model, n_samples)
    
    # Adjust synthetic data using covariance
    final_synthetic_data = adjust_with_covariance(df, synthetic_data)
    save_synthetic_data(df, final_synthetic_data, output_file)
#     final_synthetic_data.to_csv(output_file, index=True)
    
    return final_synthetic_data

# Example usage
if __name__ == "__main__":
    # File path of the example Iris dataset (modify as needed)
    input_file = "iris_data3.csv"
    output_file = "synthetic_iris_data3.csv"  # Output CSV file path

    
    # Generate 100 synthetic samples
    synthetic_data = main(input_file, output_file)
    
    print(synthetic_data)


Synthetic data saved to synthetic_iris_data3.csv
[[6.54108313 2.51526833 5.46879285 1.58757108]
 [6.26305515 3.13067743 5.30696275 2.53390984]
 [6.92493387 3.08760777 5.42015511 2.09698564]
 ...
 [7.33408087 3.55655211 6.176495   2.14692771]
 [6.39990897 2.97731302 5.29700313 2.0160775 ]
 [7.56207429 2.91160464 6.13901896 1.90901892]]
